### ISSUE TITLE
Issues with open track (duet mode)

### ISSUE THREAD

**Issue by Daniel20Ultrastar-es** [SarutaSan72/Yass#110]
Feature add track from file makes a mess right now:

First, when you add a track automatically saves the original txt by modifying its contents. The txt NEVER should be saved until you press the save button or you accept by  a warning"popup". It would be advisable to create a copy of the file and also ask the user what name to use and where to save it.

Second, the title name should not be replaced with the MULTI tag, this is already taken care of by the game to differentiate which is the duet and which is the original.

Third, tracks should be added to the MULTI file only, the other file is the original one I mentioned in the first paragraph, so, there are no files P1, P2.... for the rest, good job

**Comment by SarutaSan72** [comment]
Thanks, you're fast. Planned for next update, possibly as: 

- 'open' duet = split duet to temporary tracks in ~/.yass/ + backup
- 'save' duet = merges them back to original duet file
- 'add track' = 'save as duet' dialog + create the above trackfiles + don't touch original

**Comment by SarutaSan72** [comment]
Done in new version 1.4.1; plan to release it before Christmas
Looking forward to your feedback

**Comment by SarutaSan72** [comment]
Just released new version; wish you a happy christmas!

**Comment by Daniel20Ultrastar-es** [comment]
perfect, great work as usual, happy christmas for you too ^_^
