### ISSUE TITLE
Odd numbered page break and start time gives duet track erroneous offset

### ISSUE THREAD

**Issue by angs** [SarutaSan72/Yass#119]
An almost-minimal test track for Yass 2.4.1 (using .jar on Linux)

> #TITLE:Test
> #ARTIST:Test
> #MP3:Test - Test.mp3
> #BPM:246
> #DUETSINGERP1:P1
> #DUETSINGERP2:P2
> P 1
> : 0 3 0 One
> : 9 3 0 one
> \- 13
> : 15 3 0 two
> : 20 3 0 two
> P 2
> : 15 3 0 two
> : 20 3 0 two
> E

Even though P1 and P2 share the same line, the off-numbered page break makes Yass show P2's line off sync. Changing 13→14 and both 15→16 stops this.

**Comment by SarutaSan72** [comment]
Yes, I can reproduce it. Thanks for the minimal example! Also: after the changes, the matching notes are not detected as "same".
