### ISSUE TITLE
OGG support

### ISSUE THREAD

**Issue by Tirgatt** [SarutaSan72/Yass#122]
Some of my songs that I use with UltraStar Play are in OGG format instead of MP3. Since I sync them between my Windows computer and a Raspberry Pi, it would be great if I could keep them as OGG.

For the lower SD card space in the Raspbery Pi setup and the lower data traffic for syncing, it would be much appreciated if Yass supports OGG.

**Comment by SarutaSan72** [comment]
Duplicated #11
