### ISSUE TITLE
Uncommon whitespace

### ISSUE THREAD

**Issue by SarutaSan72** [SarutaSan72/Yass#123]
Whitespace can be put before or after a word. Yass marks 'uncommon whitespaces' that are put after a word, and provides auto-correction to move it before the next word. Some users prefer the opposite --> let user choose by adding an option.

Example

A) After a word (after common_, you can see it if you mark the text)
```
: 0 2 0 Un
: 3 2 0 common 
: 6 2 0 space
```
B) Before a word (before _space)
```
: 0 2 0 Un
: 3 2 0 common
: 6 2 0  space
```
Yass corrects A) to B), some other tools, B) to A).

**Comment by SarutaSan72** [comment]
The actual detection/correction and option are easy to change. I see difficulties in changing the lyrics editor and syllable processing, because there the behavior is hardcoded. 

Maybe easier to change the 'other tool' (USDX lyrics helper?).

**Comment by DoubleDee73** [comment]
Changed the behaviour. See https://github.com/SarutaSan72/Yass/pull/133

**Comment by SarutaSan72** [comment]
**"won't fix"** here, see the discussion above. If you want this feature please have a look at DoubleDee72's 'Yass Reloaded' fork.
