### ISSUE TITLE
Migrate to Java 17

### ISSUE THREAD

**Issue by DoubleDee73** [SarutaSan72/Yass#137]
LTS for Java 8 has run out over a year ago, thus the software should be migrated to Java 17 which is currently the version with LTS.

There might be minor challenges:
- YassMain extends JApplet which is deprecated since Java 9 and is marked for deletion. Can probably be replaced by JFrame
- YassSongList#hasNewSongs calls the static method yield withoud Thread as qualifier, which causes a problem as 'yield' is a reserved keyword from Java 13 onwards 
- Minor usages of deprecated methods, e. g. new Integer(i) instead of Integer.parseInt(i)

**Comment by SarutaSan72** [comment]
Not needed now, Java 8 still works with current OS. 
-> close
