### ISSUE TITLE
Can't choose a speed intermediate.

### ISSUE THREAD

**Issue by Daniel20Ultrastar-es** [SarutaSan72/Yass#16]
Pressing Ctrl + I or speed button, doesn't give the option to choose 50% or 75% just normal speed 100% or super slow 25%. I've couldn't find in the preferences any option related with this feature if is it possible to change it.

**Comment by SarutaSan72** [comment]
You want that? I can give you that :)
I found on/off easier to use that stepping through three or four items. 
Your idea with the preferences is fine, I will add this.

**Comment by Daniel20Ultrastar-es** [comment]
I agree that a button is easier, and faster to use, but currently you only have super slow speed or normal. A list with items like: 25%, 50%, 75% 100% would be perfect, or each time that click on the button speed could change among all these speeds, if it isn't possible, add the function in the preferences.

**Comment by SarutaSan72** [comment]
Done. 75% was not possible, only 1/1, 1/2, 1/3, 1/4...
Therefore 100%, 50%, 33%, 25%.
