### ISSUE TITLE
Wrong limit golden notes

### ISSUE THREAD

**Issue by Daniel20Ultrastar-es** [SarutaSan72/Yass#18]
The score of golden notes should be between 1000 and 1500 point. Also, a box in the main screen to indicate your current golden notes is HIGHLY recommended.

**Comment by SarutaSan72** [comment]
This is already done.

I don't find the GOLDEN score in the USDX sources and have forgotten where it is defined. Is it convention? Only these (in UNote.pas):
```
  MAX_SONG_SCORE = 10000;     // max. achievable points per song
  MAX_SONG_LINE_BONUS = 1000; // max. achievable line bonus per song
```

Anyway, this is easy doable in the options. Currently, Yass defines common GOLDEN score as 1000 +/- 200. Whenever this is not met , error detection shows it. If inside, text is shown gray, if outside, red. Text disappears if it is very near 1000. The value in brackets tells how many beats should be marked/demarked.

For your case, just set it to 1250 +/- 250.
If you think I should set the Yass defaults to your values, convince me :-) I would say that given the above maximum of 10000, and phrase bonus 1000, golden bonus should be 1000, too. 

![gg](https://user-images.githubusercontent.com/27969336/36037695-d3ccb2de-0dbd-11e8-8737-702b05e83490.png)

![gg2](https://user-images.githubusercontent.com/27969336/36037697-d722f1aa-0dbd-11e8-8048-da0c11d76a56.png)

**Comment by SarutaSan72** [comment]
:grimacing: I did some calculation and think with golden=1250 I should set **maxPoints = 7500**.
Because golden counts twice and 7500 + 1250 + 1250 = 10000.
Agree?

Here's the complete algorithm (YassAutoCorrect.java):
```
// durationNormal = sum of all normal note lengths
// durationGolden = sum of all golden note lengths
// maxPoints = getProperty("max-points") <--- without golden
// idealGoldenPoints = getProperty("max-golden");
// goldenVariance = getProperty("golden-allowed-variance");

maxPoints += idealGoldenPoints;

// The maximum score is 10.000. Maximum phrase bonus is 1.000. 
// Notes span one or more beats, points are given per beat.
// Golden notes give double points. 
// Normally you want the maximum golden notes to be near about 1.000.
// That defines this formula:
// Golden / MaxScore = 2*SumOfGoldenBeats / (SumOfNormalBeats + 2*SumOfGoldenBeats)
// Example: Golden=1000, MaxScore=8000, TotalBeats=100 --> SumOfGoldenBeats=6

int idealGoldenBeats = idealGoldenPoints * durationNormal / (2 * maxPoints - 2 * idealGoldenPoints);

int goldenPoints = round(maxPoints * 2 * durationGolden / (durationNormal + 2 * durationGolden);

if (Math.abs(goldenPoints - idealGoldenPoints) > goldenVariance) 
   // ... message
```

**Comment by SarutaSan72** [comment]
Done in 1.9.1
