### ISSUE TITLE
Erase database

### ISSUE THREAD

**Issue by Daniel20Ultrastar-es** [SarutaSan72/Yass#22]
Currently it's impossible to reset by default the values of the options that you set in yass. It should be a button in each menu of options to reset them.

Problem number 2) When you install a new version of yass should uninstall the previous version, because currently it brings problems from the previous one.

Problem number 3) When you uninstall yass, doesn't delete correctly the program. There are traces that should be delete it like C:\Users\\[username]\\.yass

**Comment by SarutaSan72** [comment]
1) button in each menu of options to reset them
Done in 1.9.1

**Comment by SarutaSan72** [comment]
2) uninstall the previous version
That would erase the spelling dictionary and custom hyphenation. Need a more differentiated approach.

**Comment by SarutaSan72** [comment]
2) Done in 1.9.1: 
- From now on, start menu entry and install folder is named "Yass Along" without version info
- Proper uninstall of start menu entry & install folder
- Installer detects previous version and allows to deinstall it

**Comment by SarutaSan72** [comment]
3) Done. Installer now asks if .yass folder should be removed.
Since this is unsafe, I've translated the installer messages.

Daniel, do you find time to translate these texts into Spanish?

```
LangString Msg_Prev ${LANG_SPANISH} "Yass Along is already installed. $\n$\nChoose `OK` to remove the previous version or `Cancel` to cancel this upgrade."
LangString Sec_ContextMenuText ${LANG_SPANISH} "Add context menu item to text files"
LangString Sec_ContextMenuKar ${LANG_SPANISH} "Add context menu item to MIDI/Kar files"
LangString Sec_ContextMenuDir ${LANG_SPANISH} "Add context menu item to directories"
LangString ContextMenu_Edit ${LANG_SPANISH} "Edit with Yass"
LangString ContextMenu_Convert ${LANG_SPANISH} "Convert with Yass"
LangString Sec_Desktop ${LANG_SPANISH} "Create shortcut on desktop"
LangString Msg_Uninstall ${LANG_SPANISH} "This will uninstall Yass from your system."
LangString Msg_RemoveSettings ${LANG_SPANISH} "Remove user data and settings? This will delete the .yass folder in your home folder. $\n$\nChoose `YES` to remove it, or 'NO' to keep it for future use."
LangString Msg_RemoveSettingsReally ${LANG_SPANISH} "Are you sure? This will delete your personal settings and spelling."
```

**Comment by SarutaSan72** [comment]
Thanks :)
