### ISSUE TITLE
Desync among yass versions

### ISSUE THREAD

**Issue by Daniel20Ultrastar-es** [SarutaSan72/Yass#24]
There is a serious problem of desync in 1.8.1 and 1.9 (not sure in 1.8 because there is no binaries)

Please pick an old song that you have. and try with yass 1.7 and 1.9

**Comment by SarutaSan72** [comment]
Cannot reproduce.  I tried 1.9.1 and 1.7.1 (download from yass-along.com) with three different songs, all showing same result. Tested on newly installed Win10 64bit, GTX 1080.

Daniel, if you still have this issue, please send me more details on how to reproduce it. Please also test with a clean install (remove .yass folder in %USERPROFILE%).

**Comment by Daniel20Ultrastar-es** [comment]
I've moved to w10 last week too, and I don't perceive this bug too, I don't know if was from w7, or java version, or my pc. Anyway I close this commit ;)
