### ISSUE TITLE
Latest version seems not working well on windows 10 and mac

### ISSUE THREAD

**Issue by andy840119** [SarutaSan72/Yass#25]
I cannot import any .mp3 files in last Yass (1.9.1)
and file->new doesn't work
some of the funcion doesn't work as well ODOa.
![image](https://user-images.githubusercontent.com/9100368/44947393-890c5d00-ae47-11e8-989d-313ff98db0e3.png)

**Comment by a3nima** [comment]
Hello, I'm experience the same problem(s). do you know what version works on win10x64 maybe?

**Comment by andy840119** [comment]
good question.
i still have no idea

**Comment by SarutaSan72** [comment]
Fix included in new version 1.9.2
