### ISSUE TITLE
Missing translations

### ISSUE THREAD

**Issue by Daniel20Ultrastar-es** [SarutaSan72/Yass#29]
where is the translation for buttom "zurücksetzen" at settings? If a translation is missing shouldn't show it in german but english.

Is it the file yass_xx.properties up to date? it should include the: " #TODO: " on the missing translations

**Comment by SarutaSan72** [comment]
Thanks, this was hard-coded. I just updated the code, translation was already done.

If you find another one, tell me. The yass_xx.properties are up to date. For the new version 1.9.2, I just inserted the "#TODO:" for the missing translations (six lines). If you find time, go ahead, then please close this issue.

**Comment by SarutaSan72** [comment]
This seems done.

**Comment by SarutaSan72** [comment]
Switching to UTF8 introduced problems, see my comment here: https://github.com/SarutaSan72/Yass/commit/b561720cb0cb21d802698a43e1a397de8cab7cc2#commitcomment-31872274

**Comment by Daniel20Ultrastar-es** [comment]
is it solved now?

**Comment by SarutaSan72** [comment]
Yes, thanks
