### ISSUE TITLE
fit lyrics size

### ISSUE THREAD

**Issue by Daniel20Ultrastar-es** [SarutaSan72/Yass#32]
the old font which ultrastar used is outdated. We use a new font "roboto" in panoramic format. So you can add more words in just one line. Have a look: https://github.com/ultrastares/usdxworldparty/tree/master/game/fonts

Yass should read and support the font from the ultrastar font folder content

**Comment by SarutaSan72** [comment]
That would require these parameters: TTF font, GlyphSpacing, Stretch, Outline. Maybe some more hard-coded parameters from the code? In addition, the TTF depends from the actual lyrics and might be replaced with a fallback font.

The Yass algorithm uses the original Ultrastar formula.
- Font property from the settings; limited to src\yass\resources\fonts\{Font1.dat, Font2.dat}
- First 256 bytes represent character width of an ascii code. 
- Codes above 256 are matched to [W], quotation marks are matched to ['].
- Hardcoded parameters: fontSize, fontAspectRatio (W/H), character spacing, character outline, scaling, line insets.

I can think of this approach:
In a first step I would make these Yass parameters available in the settings. Then there can be a preset to approximate your approach.

**Comment by Daniel20Ultrastar-es** [comment]
it would be ok with just changing:
in Extras -> preferences -> editor -> design -> width -> 450 / size 14 (so doesn't need to change the font)
but requires to fix errors from error button

**Comment by SarutaSan72** [comment]
Changing that default value will merely affect the UI design, not error checking.

Another idea: 
- convert the new font to .dat format
- and include it in settings->errorchecking->others->fonts 

Please tell me which Roboto font you use. 
(The download from https://fonts.google.com/specimen/Roboto contains 12 different TTF files.)

**Comment by Daniel20Ultrastar-es** [comment]
Changing just that value, after restart yass, the UI is readapted, but if it fail in your new design I attach you the font: 

https://github.com/ultrastares/ultrastar-worldparty/tree/alfa/game/fonts/Roboto
(Roboto regular)

(thank you for your work)

**Comment by Daniel20Ultrastar-es** [comment]
Changing just that value, after restart yass, the UI is readapted, but if it fail in your new design I attach you the font: 

https://github.com/ultrastares/ultrastar-worldparty/tree/alfa/game/fonts/Roboto
(Roboto regular)

(thank you for your work)

**Comment by SarutaSan72** [comment]
There is no easy solution to include the Roboto font.
I'll stick to your suggestion, just set width = 450.
--> Done & close; new default value will be included in next release.

**Comment by Daniel20Ultrastar-es** [comment]
did you contemplate the error "line overflow" from "error button" when the lyrics width is higher 400 but lower of 450?

**Comment by SarutaSan72** [comment]
No. So you want to change the limit for the "line overflow" error. --> i'll check, reopen

**Comment by SarutaSan72** [comment]
Hi Daniel, I have committed new options
- Arial Bold (USDX OLine1), Candara Bold (USDX OLine2), Roboto Regular (yours). 
- or select any local TTF file
- font size (default 28)
- character spacing (default 0)
- display width (default 800)

I have included only character widths because licensing prevented me from including the TTF. 

If you want me to include character widths for some other TTFs, please tell me.

Could you please translate these texts? Thanks in advance.

```
options_errors_fonts = Text
options_errors_breaks = Page breaks
options_errors_bonus = Bonus

options_errors_font_file = Fuente:
options_errors_font_file_comment = For checking text width against display width.
options_errors_font_size = Font size
options_errors_font_spacing = Character spacing
options_errors_font_spacing_comment = Additional distance between letters.
options_errors_font_max_width = Display width
options_errors_font_max_width_comment = Max. allowed text width
```

**Comment by Daniel20Ultrastar-es** [comment]
done

**Comment by Daniel20Ultrastar-es** [comment]
I had a problem with the update.

What codification do you use for translation files ANSI or UTF8?

**Comment by TeLiXj** [comment]
> I had a problem with the update.
> 
> What codification do you use for translation files ANSI or UTF8?
> 
> Edit: it seems to be ANSI (Done)

I think that translations must be in UTF8... but I supose that will be a new issue

**Comment by SarutaSan72** [comment]
Thanks, done! New release will be available in a few minutes...
