### ISSUE TITLE
add piano scales number and colorized

### ISSUE THREAD

**Issue by Daniel20Ultrastar-es** [SarutaSan72/Yass#34]
Would be great if yass will introduce the scales notes colorized.

Each scale will take a color, and also the number will be shown both in the piano as in every syllable.

I made a mockup in paint to have a look: https://i.imgur.com/Gss5lz5.png (I made the font too big, but should be smaller to fit in)

The colors scale should be like the rainbow does. (but being noticeable every scale)

**Comment by SarutaSan72** [comment]
No need to show the scale at every note and overwhelm the user with colors. For short notes, This would make note name and note length less readable. See the red circles in this example:  https://i.imgur.com/8QCGe6A.png

There, the red arrow shows my counter-proposal: show the scale as small number aside the C notes.

**Comment by Daniel20Ultrastar-es** [comment]
Then don't show the number scale in note names to fit in (in your red circles), but, put colors in note name instead, just to know where am i. The way you pretend to put the number just in C notes in the piano it's insufficient for me. It will much easier for beginners to know what key are you playing.

If you still don't like the idea, could be possible to customize this for the user instead? For example (Show / hide the name notes or give colors to scales)

**Comment by SarutaSan72** [comment]
If you really really want this. Adding options requires more implementation/translation, plus the extra work for adjusting code (move labels when they overlap).

I'll wait a few days, maybe we find a better design?

**Comment by SarutaSan72** [comment]
btw, did you try Ctrl-PageDown ? This shows scale jumps very quickly.

**Comment by Daniel20Ultrastar-es** [comment]
that select everything, it doesn't show the scale that you are at.

(let me find other designs in a few days)

**Comment by SarutaSan72** [comment]
can you explain why you need it? Maybe I did not understand the reason why this is urgent. Different scales are no problem for pitch detection, and if lines have different scales, it becomes immediately visible in multipage/selectall view.

**Comment by Daniel20Ultrastar-es** [comment]
who said it was urgent?. Yes I know the pitch detection thing, however, when you start a song from 0, and you don't use a midi, but put notes by ear instead, it's easier to know in which scale you are, also help you learning playing the piano and makes you understand better the music. This thing will allow you create faster songs than playing "blind".

**Comment by SarutaSan72** [comment]
Wow, this is something! You know, I cannot think of putting notes by ear. Therefore I did not understand why this would help. All fine now, thanks for the explanation.

**Comment by SarutaSan72** [comment]
done. I paint the scale at left/right borders and alternate backgrounds only in grayscales (sorry, I want to reserve colors for golden/freestyle/errors/selection). The new overview shows wrong scales immediately. Screenshot: https://i.imgur.com/gUnP0Mk.png
