### ISSUE TITLE
Improve workspace

### ISSUE THREAD

**Issue by Daniel20Ultrastar-es** [SarutaSan72/Yass#35]
This one is related with #34 . I've spent a few hours making a new mockup a little bit more "professional".

Basically the changes are in the image.

Original one: https://i.imgur.com/b5pIsj3.jpg

New workspace: https://i.imgur.com/fm0rtjz.jpg

Hope you like the idea. Let me know what do you think.

if you don't like the colored screen could be optional for users in settings or another idea is to bring the colors when piano is activated, if the piano is disable then come back to white screen.

(This could be the 2.0 version of yass)

**Comment by SarutaSan72** [comment]
Yes, it absolutely makes sense to use the free space.

**Comment by SarutaSan72** [comment]
Most things are done as part of #36.
Extracting the lyrics from the sheet is not straightforward --> postponed

**Comment by SarutaSan72** [comment]
Hi Daniel, the new release is published. I hope you like it, it includes most of your input.
You can activate note scale at each note in the settings.
Lyrics are still in the same panel as the notes, it is not easy to extract them.

**Comment by Daniel20Ultrastar-es** [comment]
I only can see the scale in every note, but not when starts and ends... How can I set the scale number on the left as in the picture?

**Comment by SarutaSan72** [comment]
Switch from relative (single page) to absolute note heights.
- press page down a few times
- or respective page++ button (top right)
- or drag transparent background
-or select multiple lines

**Comment by Daniel20Ultrastar-es** [comment]
it should appear the scale number when piano button is activated.

BTW, all scales are wrong right now, most of them shows in scale 1 but should be in scale 5

**Comment by SarutaSan72** [comment]
done, see release info 2.0.1

**Comment by SarutaSan72** [comment]
Created follow-up ticket #41, closed this one
