### ISSUE TITLE
Keyboard shortcut for slide action

### ISSUE THREAD

**Issue by SarutaSan72** [SarutaSan72/Yass#37]
Visible area can be slided horizontally by dragging the transparent area with the mouse (cursor becomes the hand symbol). There is no keyboard shortcut for this.

-->  Shift+MouseWheel or Ctrl+Alt+Left/Right

**Comment by SarutaSan72** [comment]
problem: wheel action is handled by base class of lyrics area (TextArea)

**Comment by Daniel20Ultrastar-es** [comment]
in my opinion, if you can't set the scroll with the hover, set the scroll for the notes (left to right) and add 2 button up and down for the lyrics
