### ISSUE TITLE
Maintainer?

### ISSUE THREAD

**Issue by achimmihca** [SarutaSan72/Yass#46]
Hello,
I want to contribute and maintain this project. It is the best editor for UltraStar songs that I found. It would be a shame if it is not further continued. Could you add me as maintainer, please? I have some ideas for improvements.

Regards,
Andreas Stange

**Comment by Mitmischer** [comment]
Maybe you should fork the repo and integrate your improvements there :+1:

**Comment by achimmihca** [comment]
I considered contributing to Yass.
However, I decided to focus on [Ultrastar Play](https://github.com/UltraStar-Deluxe/Play) instead because I see its potential for a new cross-platform USDX with an integrated editor. It's a project in its infancy but with potential nonetheless.

Furthermore, the monolithic class YassSongList, which has more than 6000 lines of code and methods spannig hundreds of lines, scared me of.
Still, Yass is the best editor for UltraStar songs at the moment.
