### ISSUE TITLE
Save txt in UTF8 without BOM

### ISSUE THREAD

**Issue by TeLiXj** [SarutaSan72/Yass#50]
Hi! 
Currently if you edit a txt codified in UTF8 without BOM and save it, is converted to UTF8 with BOM and this could cause problems if you edit these txt in other editor.

I hope that you can fix it :)

**Comment by TeLiXj** [comment]
I didn't see the option in extension section to change it. I think that must be checked by default.

**Comment by SarutaSan72** [comment]
Now checked by default. Will be included in upcoming version 2.1.
