### ISSUE TITLE
Add rap notes support

### ISSUE THREAD

**Issue by TeLiXj** [SarutaSan72/Yass#51]
Currently if you edit a song with rap notes and save it are been commented
```#R 1051 3 1  de
#R 1054 3 1  no
#R 1059 1 1 che
```
and must count to golden notes calculation

**Comment by Daniel20Ultrastar-es** [comment]
we use 'R' for rap notes and 'G' for golden notes

R 0 2 1 This
R 4 2 2 is
G 6 3 1 an
G 9 1 1 ex
G 10 2 2 am
G 12 2 1 ple

for yass it would be treated like a normal and golden note, but writing in the files 'R' or 'G' instead of ':' and '*'

**Comment by SarutaSan72** [comment]
please could you mail me an example textfile ?

**Comment by SarutaSan72** [comment]
Hi Daniel, no need for sending me an example file.

This is done & included in next release.
