### ISSUE TITLE
BUG: Errors while loading midi file

### ISSUE THREAD

**Issue by Tauvic** [SarutaSan72/Yass#52]
I tried to load a midi file but that failed. Yass tries to load a midi resource file AJH_Piano.sf2 and it fails to find it in its own jar in the right place. I manualy added this file in the jar file and then its able to find, load and continue.

Please update the code bug to find this resource in the right place.

**Comment by SarutaSan72** [comment]
Code now points to correct location in jar file. 
Bugfix will be included in next release 2.1.
