### ISSUE TITLE
Poor contrast in dark mode

### ISSUE THREAD

**Issue by Daniel20Ultrastar-es** [SarutaSan72/Yass#58]
I attach you a screenshot about the issues.

https://i.imgur.com/BOnC1F4.png

Can you make the UI darker? (& set text in white)

**Comment by SarutaSan72** [comment]
Helpful feedback, I'll change that this weekend.

**Comment by Daniel20Ultrastar-es** [comment]
I send you a 2nd part in a picture:

https://i.imgur.com/2Q6lmol.png

(Thank you so much for your work) ;)

**Comment by SarutaSan72** [comment]
Done
- above issues
- removed white panel borders in dark mode
- lyrics scroll bar dark mode
- removed up/down buttons from lyrics scroll bar 

New version 2.1.1 is online.

Created issue #59 for the icons, which currently cannot be used in dark mode.
