### ISSUE TITLE
Rap notes don't have colors

### ISSUE THREAD

**Issue by Daniel20Ultrastar-es** [SarutaSan72/Yass#62]
it's quite confusing to tell the differences rap notes from the rest. Rap notes and golden rap notes should have their own color.

**Comment by SarutaSan72** [comment]
done, incluede in next release 2.1.2

**Comment by Daniel20Ultrastar-es** [comment]
Do you mind if you change the colors?

I think it will be better to use: 
yellow for golden notes
Orange for golden rap notes
green for raps notes
pink for freestyle notes
Apply light colors for all of them and use a dark one when a note is selected.
