### ISSUE TITLE
Improve edit lyrics

### ISSUE THREAD

**Issue by Daniel20Ultrastar-es** [SarutaSan72/Yass#70]
I think all song creators, we had always the same issue several times. We don't know when the lyrics section is active or not to edit the text.

It would be great to block the lyrics, so when you click on the syllable, it will load the line of that syllable but unable to edit.

on the other hand, you could put on the right button of the mouse the option "edit lyrics" (or create a new button in the tool bar) where you can't select the notes, but only edit the text, in addition, the lyrics panel should change color when you enter in "edit mode" to let you know that you are editing.

**Comment by SarutaSan72** [comment]
> > you could put on the right button of the mouse the option "edit lyrics" (or create a new button in the tool bar) where you can't select the notes, but only edit the text,

when you click the right button in the lyrics area, it will enter edit mode. Why an extra edit button?

> > lyrics panel should change color when you enter in "edit mode" to let you know that you are editing.

absolutely yes. the current color change is not visible, I'll improve that

**Comment by SarutaSan72** [comment]
I improved coloring to make the edit state (on/off) more apparent. 
Daniel, please have a look if this fixes this issue.

I am not sure if I understood your explanation.

**Comment by Daniel20Ultrastar-es** [comment]
yes, it's perfect. Thank you
