### ISSUE TITLE
Some layout issues...

### ISSUE THREAD

**Issue by bigboss97** [SarutaSan72/Yass#72]
1) In dark mode, those little squares are irritating.
2) The line numbers on red background are barely visible.
3) Can I increase the font size of the lyric line at the bottom separately?
![Screenshot - 20-05-09 17 57 58](https://user-images.githubusercontent.com/34834507/81467902-1d36e600-921f-11ea-85a7-87dac7780273.png)

**Comment by SarutaSan72** [comment]
1. + 2. please have a look at new version 2.1.2 (coming this afternoon)
3. no sorry, only the font size of the lyrics area. I could add it, but not now, holiday ends. Do you have a hi-res monitor?

**Comment by bigboss97** [comment]
1 & 2 Thanks
3 Not really, it's just like full HD TV and I even scaled up everything:
![Screenshot - 20-05-09 21 51 06](https://user-images.githubusercontent.com/34834507/81473052-744cb300-923f-11ea-9724-e541e4d21f00.png)
