### ISSUE TITLE
Chinese hyphenation

### ISSUE THREAD

**Issue by bigboss97** [SarutaSan72/Yass#73]
Can you please add Chinese hyphenation?
It's very simple. In Chinese, each word (one UTF-8 character) has exactly one syllable. Basically you only have to place a hyphen everywhere between two characters.

**Comment by SarutaSan72** [comment]
I am using David Ashen's hyphenation tool (http://www.davidashen.net/texhyphj.html). Now I have added the Chinese TeX hyphenation patterns from [https://tug.org/tex-hyphen/](https://tug.org/tex-hyphen/), but it doesn't hyphenate my sample text.

You can try yourself with the new version 2.1.2. During "New...", select ZH for hyphenating the text. 

Maybe I have used the wrong hyphen file. You can try searching some other hyphen file and store it as  **$home/.yass/ZH.tex** Reload Yass and try again.

If you have success, tell me which hyphenation patterns you use and I will include them.

**Comment by bigboss97** [comment]
OK, will do, thanks.

**Comment by bigboss97** [comment]
I had a look in the pinyin.TeX. It looks like that is for pinyin, i.e. when Chinese is written in Latin letters with vowels and consonants.
When Chinese is written in traditional characters it doesn't need any hyphenation rules, because all words have the same length. Therefore Chinese words are not separated by space.
In case of karaoke, we need only one rule, namely one hyphen between two words (UTF-8 character).

**Comment by SarutaSan72** [comment]
Then I have to do it in code. --> next version, no more holiday

**Comment by SarutaSan72** [comment]
Included in upcoming release
