### ISSUE TITLE
Integrate the a auxiliary note technique

### ISSUE THREAD

**Issue by TeLiXj** [SarutaSan72/Yass#74]
To make songs we use the auxiliary note technique, that consists in create a new note only to help to synchronize. Others, like me, use the previous, the next or move the same note to check when start or finish the current note. Both do the same using a different way and I want to do this directly with a new Yass enhancement.

Now you have 2 buttons to play, one to play the current note and other to play the whole line. Well, I suggest to add 2 buttons more to play X tiles before the note starts and other to do the same after it and a 2 select box to choose how many tiles play for each one.
![imagen](https://user-images.githubusercontent.com/5677943/81470800-155e4e00-91ed-11ea-9928-4d62ad3b965b.png)
And of course adding the shortcuts Space+B to play previous notes and Space+N to play the following notes.

I think that could be relative easy to implement

**Comment by SarutaSan72** [comment]
Nice idea. I belong to the group that "move the same note to check when start or finish the current note", but this "play before/after" is really more direct --> next version

**Comment by bigboss97** [comment]
It would be great if we can use modifier key combination, e.g. Ctrl+Space etc. Then we can allow playing notes in editor mode.
Currently, when I'm changing something in editor I have to leave editor to play the notes because the space is used for text input.

**Comment by SarutaSan72** [comment]
Done. I'll wait for your feedback before publishing the new release. 

https://yass-along.com/data/downloads/yass-installer-2.2.0.exe
https://yass-along.com/data/downloads/yass-2.2.0.jar

- Provided two buttons to play 300ms before (**B**) and next (**N**)
- No X-tiles buttons
- No Ctrl key needed
- Icons changed, see image

![bf](https://user-images.githubusercontent.com/27969336/102914304-58211d80-4480-11eb-8743-84bf809a5f04.png)

Please could you 
- tell me if I can close this issue? (I am unsure about the 300ms range, but these X-tiles buttons are awkward to implement)
- provide Spanish text (as comment here) for "Play before" and "Play next", or a similar one including **B** and **N**, if possible.

Have a nice christmas!

**Comment by TeLiXj** [comment]
Wow! Works fine!!! The icons are perfect.
But you may include a new option to change that 300 ms, maybe in the next version

The translations:
Play before -> Reproducir antes
Play next -> Reproducir después

And change translations of letter position in the layout, if you can too :)
West -> Izquierda
East -> Derecha

It's a very nice work. Thank you and happy christmas!!!!

**Comment by SarutaSan72** [comment]
Thanks! I just have published the new version. The option to change that 300ms is included.

**Comment by SarutaSan72** [comment]
Improve this for page start/end to avoid changing pages.
Play actual gap (keys B/N) or play short range (Shift+B/N). 
N key sometimes does not work.

**Comment by SarutaSan72** [comment]
should be fixed in upcoming release 2.2.1

**Comment by SarutaSan72** [comment]
New version is online. Note that I have changed “play before/next”:
- the action (B/N) now plays the gap before/after the selection.
- Shift+B/N plays 300ms before/after it (as in v2.2.0)
