### ISSUE TITLE
Feature request: A balance slider for audio and melody/beats

### ISSUE THREAD

**Issue by bigboss97** [SarutaSan72/Yass#75]
When I'm editing I like to listen to the melody. But I couldn't find where I can make the piano softer.
I wish there's a slider which allows user to balance the audio and melody.

**Comment by SarutaSan72** [comment]
You can play piano without audio (shift+space) or switch (space, ctrl+space, shift+space).
I'd like to have feedback from other users if this is really needed.

**Comment by Daniel20Ultrastar-es** [comment]
(in my case, I don't consider relevant increase/decrease the piano volume)

**Comment by bigboss97** [comment]
> You can play piano without audio (shift+space) or switch (space, ctrl+space, shift+space).

Yes, I keep on switching back and forward.
I had situations, where in one long syllable there are two MIDI notes. I tried to match the two notes with one syllable and decide whether I should delete one of the notes.

> I'd like to have feedback from other users if this is really needed.

Certainly. Maybe I'm the only one.
I can't play any music instrument and my pitch hearing is poor :-)

**Comment by SarutaSan72** [comment]
Little relevance, closed.
