### ISSUE TITLE
Page break timestamp is higher than the following text event

### ISSUE THREAD

**Issue by bigboss97** [SarutaSan72/Yass#76]
I'm using v2.1.2 (WIndows 10).
I created the project by adding a MIDI and paste the lyrics (from an old MIDI-KAR project, with dashes and line breaks).
Then I started moving the text elements to match the MP3 audio. Obviously the page break didn't move along with the line break:
![Screenshot - 20-05-19 09 45 30](https://user-images.githubusercontent.com/34834507/82275544-64af3600-99c6-11ea-964d-d911b8db22a8.png)
The green arrows show the line break. The pink arrows show the page break which has the value 92 and that appears before 88. Vocaluxe is confused with that.

I'm quite new in Yass. Maybe I have done something wrong. I did try to use the toolbar:
![Screenshot - 20-05-19 11 52 09](https://user-images.githubusercontent.com/34834507/82276033-84932980-99c7-11ea-96c8-aa2af4da608e.png)
Somehow I didn't get it to work or maybe I don't understand.
So I purely use the text editor to add ~ and -. Then move them in the timeline. I'm very comfortable with that. But now I have the page break problem.

I also noticed, when I insert a text element the last element in the line is pushed to next page because the following note is in the next page. So the last syllable automatically go to the next line. Every time I had to fetch it back to the current line. All these had caused my page break problem.

Proposal:
When the last syllable of a line is pushed to the next note the page beak extends to the next note to keep the element in the same line.

**Comment by SarutaSan72** [comment]
For personal reasons I am very limited in time and cannot provide any support in finetuning. 

I understand that I am missing advice on finetuning songs. I can add that but not in near future. If someone else reads this, I'd appreciate if (s)he can provide a link to a (legal) guide, or even add basic instructions here.

Now, having said this, I can make an exception here... 

My general advice:
- before finetuning
  - assure you have 300-400 bpm
  - start with separating words into syllables, one note for each syllable
  - then move each line to its estimated position
- then start finetuning 
  - always separate words (by gaps)
  - separate syllables, if possible
  - shorten the notes as much as possible, especially for words having silent endings.
  - if a page break seems impossible, rehear your line and move/shorten the last note, or move the next note
- remember you can copy/paste repeating melodies

In your case, I'd reduce the C_2 note to C_1 and possibly move the D#_3 note one beat to the right. And double-check the bpm.

**Comment by bigboss97** [comment]
> For personal reasons I am very limited in time and cannot provide any support in finetuning.

Not a drama.
btw, the software is great (very powerful). I'm trying to get familiar with it. When I get the time I'll do a tutorial to help others, too.

> auto-correct minor errors (there is an option to auto-adjust page breaks when moving notes)

Looks like this is what I need. I just have to find it  :-)
I fixed my problem by moving the page break manually.

> always separate words (by gaps)

Chinese words are written without space. That's the reason I'm using dash.

Thanks for your time.

**Comment by SarutaSan72** [comment]
Integrated into https://yass-along.com/faq/
Close this issue.
