### ISSUE TITLE
Display (on/off) Mic Notes

### ISSUE THREAD

**Issue by Nada647** [SarutaSan72/Yass#77]
Would it be possible to add a button to display the last mic notes, instead of having them disappear ? It would be great to speed up the song creations. 
(love the last version btw)

**Comment by SarutaSan72** [comment]
(thanks :)

Not sure if I understand this. After recording the location of the selected notes, their locations are directly applied to the selected notes. So displaying them would not help, since they match exactly the now-adapted notes?

**Comment by Nada647** [comment]
Hello,

Sorry, my English is quite bad ;)
When you hit play (not record), if you sing, the notes are displayed, but after that, they disappear. I thought it would be helpful to have the ability to display them while setting the notes at the desired height. It would sure help me to speed up the process.

Hope it’s clearer now, tell me what you think...

Yann

**Comment by SarutaSan72** [comment]
Funny, I forgot about that. Never used that feature :)

Yes, this could be changed, but with very low priority.

**Comment by Nada647** [comment]
Thanks for your reply and your time !

Yann

**Comment by SarutaSan72** [comment]
clearing all outdated issues.
won't fix this.
