### ISSUE TITLE
Load spectrogram as background

### ISSUE THREAD

**Issue by juergendrachta** [SarutaSan72/Yass#78]
For easier pitch correction and note alignment, I'd propose to add the functionality to load a **spectrogram as background in the edit mode**.

Of course, the spectrogram needs to be adjusted beforehand, i.e. the first pixel bottom left must be for t=0s and f=C0.

The background is the following: 
I'm working on a semi-automated process for creating USDX files. This involves pitch detection and note extraction which yields me a spectrogram, which be very handy to include for finetuning the UDSX notes. For note extraction, I use [Tony](https://code.soundsoftware.ac.uk/projects/tony) after having separated off the vocals using [spleeter](https://github.com/deezer/spleeter). The spectrogram then looks like
![spectrogram](https://code.soundsoftware.ac.uk/attachments/download/1069/tony-screeny-20140328-30pc.png)

And thank you for sharing your project!

**Comment by SarutaSan72** [comment]
Long ago I made some [accuracy tests](https://yass-along.com/about-accuracy/) and therefore displayed waveforms. It is still there: Extras -> Preferences -> Debug -> Accuracy -> Show waveforms.

That feature is only experimental and left for others to fork & refine.

**Comment by juergendrachta** [comment]
Thanks for your reply!

This is almost, what I requested for! 
If we could apply a Fourier transformation on the waveform, it'd be it!

But thanks for your hint, know I that the waveform functionality could be starting point for me!

Coming from backend development and data science in C++ and python, everything related to Java and especially JWT is quite knew to me, but I'll play around a bit to get a spectrogram in!
