### ISSUE TITLE
export and generate midi from yass synchronized file

### ISSUE THREAD

**Issue by mustangfred** [SarutaSan72/Yass#79]
Hello,

Is it possible to generate a midi file from the generate txt file from yass with good pitch and good synchro. The opposite of one option I used a lot. 
Because I have some friend that help me to correct the pitch in yass and they would like to use our work to finalise a lot of midi files

Fred

**Comment by SarutaSan72** [comment]
Given my lack of time, I'd suggest doing some research on "converting csv to midi". CSV seems to be a common text-based format, supported e.g. here
- https://melanchall.github.io/drywetmidi/api/Melanchall.DryWetMidi.Tools.CsvConverter.html
- https://www.fourmilab.ch/webtools/midicsv/
- and possibly better ones, I just googled two minutes
Then all you have to do is converting your text format to CSV, e.g. in MS Excel.

If you find a solution, feel free to report it here.

**Comment by SarutaSan72** [comment]
closing this question, please refer to some of the referenced tools
