### ISSUE TITLE
Remove the Ctrl+D keyboard shortcut

### ISSUE THREAD

**Issue by MairusuPawa** [SarutaSan72/Yass#88]
Hello!

Ctrl+D (and Ctrl+M) are more or less undocumented features in Yass. I don't think you can currently double or divide by 2 the BPM just by using the application's menus.

Unfortunately, having Ctrl+D as a shortcut to divide by 2 the current file's BPM causes a few issues. There's no confirmation asked. There's no way to undo it (doesn't work). And, it's very easy to accidentally hit that command instead of Ctrl+S when trying to save a file.

I think those two advanced features should absolutely remain available in YASS (they are indeed sometimes really useful), however, not as hidden keyboard shortcuts.

Thanks!

**Comment by SarutaSan72** [comment]
true, I will remove them --> assigned

**Comment by SarutaSan72** [comment]
- Done in master branch, will be included in next release 2.3.1
- Updated online help: https://yass-along.com/beats/
- Added proper lyrics gap marker
- Added help button for gap/bpm dialog
- Fixed initial position of gap/bpm dialog
- Fixed: update gap dialog when changing gap by keyboard shortcuts
